#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

ifconfig lo 127.0.0.1 up
udhcpc -i eth0 >/dev/null 2>&1 || udhcpc -i enp0s3 >/dev/null 2>&1 || true

exec 0</dev/tty1
exec 1>/dev/tty1
exec 2>/dev/tty1

clear

if [ -f /installer/setup.elf ]; then
    chmod +x /installer/setup.elf
    /installer/setup.elf
else
    echo "HATA: Kurulum dosyasi bulunamadi!"
    exec /bin/sh
fi
